// Dense parity check: 720 frames (9 states × 2 sizes × 40 timestamps across
// several full animation cycles — the circle→triangle→square→circle morph,
// the rubik scramble/solve/rest loop, strand drift, signal re-picks, …)
// generated by running the ORIGINAL TypeScript engine unmodified
// (tool/gen_dense_golden.mjs). The fixture is excluded from the published
// package; the test is skipped when it is absent.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ai_motion_fx/src/engine/mode_frames.dart';
import 'package:ai_motion_fx/src/engine/particle_system.dart';
import 'package:ai_motion_fx/src/models/thinking_orb_config.dart';
import 'package:ai_motion_fx/src/models/thinking_orb_state.dart';

import 'golden_compare.dart';

void main() {
  final file = File('test/fixtures/dense/orbs-dense.json');
  if (!file.existsSync()) {
    test('dense golden (fixture not present)', () {}, skip: 'fixture excluded');
    return;
  }
  final cases = (jsonDecode(file.readAsStringSync())['cases'] as List).cast<Map<String, dynamic>>();
  final fb = FrameBuilder();
  for (final state in ThinkingOrbState.values) {
    for (final size in [64, 20]) {
      test('${state.name} @$size — all timestamps', () {
        final cfg = ResolvedOrbConfig.resolve(
            state, size == 20 ? OrbTuning.compact : OrbTuning.standard);
        final mine = cases.where((c) => c['state'] == state.name && c['size'] == size);
        expect(mine.length, 40);
        for (final c in mine) {
          final t = (c['t'] as num).toDouble();
          modeFrameFor(cfg.mode)(fb, size.toDouble(), t, cfg.opts);
          try {
            expectFrameMatches(
              fb,
              want: (c['dots'] as List).cast<num>(),
              wantLines: (c['lines'] as List).cast<num>(),
              dotCount: c['n'] as int,
              lineCount: c['nl'] as int,
            );
          } catch (e) {
            fail('t=$t: $e');
          }
        }
      });
    }
  }
}
